version: '3.7'

services:
  web:
    build: ./nginx/
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt/live/xsinator.com/fullchain.pem:/etc/letsencrypt/live/xsinator.com/fullchain.pem
      - /etc/letsencrypt/live/xsinator.com/privkey.pem:/etc/letsencrypt/live/xsinator.com/privkey.pem
      - ./app:/var/www/html
      - ./src/leaks:/var/www/src/leaks
      - ~/logs/:/var/log/nginx/:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/xsinator.com.conf:/etc/nginx/sites-enabled/xsinator.com.conf
    depends_on: 
       - phpfpm
       - ws
    networks:
       - appnet


  phpfpm:
    image: php:fpm
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html:ro
    networks:
      - appnet

  ws:
    build: ./ws/
    restart: unless-stopped
    networks:
      - appnet


networks:
  appnet:
    name: appnet

